nginx create
nezavisimost/FuckRKN1 pull request #71
Opened 2022-07-28 17:03 UTC by KnyazkovE

скрипт + конфиг

2022-07-28 21:21 UTC, er2805620 commented
sudo cp ./web-server.conf /etc/nginx/conf.d/

not good place
https://docs.nginx.com/nginx/admin-guide/basic-functionality/managing-configuration-files/
conf.d/
set of feature‑specific files stored in the /etc/nginx/conf.d directory and use the [include](https://nginx.org/en/docs/ngx_core_module.html#include) directive in the main nginx.conf file to reference the contents of the feature‑specific files.


So
```
sudo cp ./web-server.conf /etc/nginx/sites-available/
sudo ln -s /etc/nginx/sites-available/web-server.conf /etc/nginx/sites-enabled/
```

2022-07-29 07:54 UTC, the2pizza commented on setup/nginx-web/nginx-install-ubuntu.sh
> +curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
Currently the script is not idempotent. (If i run it second time It fails) Nice to have the ability to run it multiple times without side effects

2022-07-29 07:55 UTC, the2pizza requested changes
Please take a look at my comment about the script

2022-08-04 15:02 UTC, the2pizza commented
done - https://github.com/nezavisimost/FuckRKN1/pull/83

2022-08-04 15:02 UTC, closed without merging